// Demo data for offline mode
import { Product, User } from '@/lib/supabase';

export const DEMO_USER: User = {
  id: 'demo-user-id',
  email: 'demo@pos.com',
  full_name: 'Demo User',
  role: 'cashier',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Espresso',
    description: 'Strong black coffee',
    price: 3.5,
    stock: 100,
    category: 'Beverages',
    sku: 'BEV-001',
    image_url:
      'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Cappuccino',
    description: 'Espresso with steamed milk foam',
    price: 4.5,
    stock: 100,
    category: 'Beverages',
    sku: 'BEV-002',
    image_url:
      'https://images.pexels.com/photos/1251175/pexels-photo-1251175.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Latte',
    description: 'Espresso with steamed milk',
    price: 4.75,
    stock: 100,
    category: 'Beverages',
    sku: 'BEV-003',
    image_url:
      'https://images.pexels.com/photos/6954201/pexels-photo-6954201.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'Croissant',
    description: 'Buttery French pastry',
    price: 3.0,
    stock: 50,
    category: 'Pastries',
    sku: 'PAS-001',
    image_url:
      'https://images.pexels.com/photos/2135677/pexels-photo-2135677.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    name: 'Blueberry Muffin',
    description: 'Fresh baked muffin',
    price: 2.75,
    stock: 50,
    category: 'Pastries',
    sku: 'PAS-002',
    image_url:
      'https://images.pexels.com/photos/2144112/pexels-photo-2144112.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    name: 'Chocolate Cake',
    description: 'Rich chocolate cake slice',
    price: 5.5,
    stock: 30,
    category: 'Desserts',
    sku: 'DES-001',
    image_url:
      'https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    name: 'Green Tea',
    description: 'Organic green tea',
    price: 2.5,
    stock: 100,
    category: 'Beverages',
    sku: 'BEV-004',
    image_url:
      'https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-8',
    name: 'Bagel with Cream Cheese',
    description: 'Toasted bagel',
    price: 3.25,
    stock: 40,
    category: 'Breakfast',
    sku: 'BRK-001',
    image_url:
      'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-9',
    name: 'Sandwich',
    description: 'Fresh deli sandwich',
    price: 7.5,
    stock: 30,
    category: 'Lunch',
    sku: 'LUN-001',
    image_url:
      'https://images.pexels.com/photos/1603901/pexels-photo-1603901.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-10',
    name: 'Fruit Smoothie',
    description: 'Mixed berry smoothie',
    price: 5.0,
    stock: 60,
    category: 'Beverages',
    sku: 'BEV-005',
    image_url:
      'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
